# -*- coding: utf-8 -*-
"""news_scaper_briefly.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SSjYozyxf78CcxCyNrDghVsVv4g9Jz19
"""

!pip install trafilatura feedparser gspread -q

from google.colab import auth
auth.authenticate_user()
print("Authenticated!")

SPREADSHEET_ID = "1cJTZrwTsBJVWF4_Nfa_Sc8TuGuagjqAF3BUFDbw7X5E"  # from the URL
SHEET_NAME     = "News"
MAX_PER_FEED   = 10   # keep low for testing

FEEDS = [
    ("CBC News",       "https://rss.cbc.ca/lineup/topstories.xml"),
    ("CTV News",       "https://www.ctvnews.ca/rss/ctvnews-ca-top-stories-public-rss-1.822009"),
    ("Global News",    "https://globalnews.ca/feed/"),
    ("CP24",           "https://www.cp24.com/rss/cp24"),
    ("Financial Post", "https://financialpost.com/feed/"),
    ("BNN Bloomberg",  "https://www.bnnbloomberg.ca/arc/outboundfeeds/rss/"),
    ("Reuters",        "https://feeds.reuters.com/reuters/topNews"),
    ("AP News",        "https://rsshub.app/apnews/topics/apf-topnews"),
    ("TechCrunch",     "https://techcrunch.com/feed/"),
]

!pip install google-generativeai==0.7.2 -q

import google.generativeai as genai
import threading
import requests

GEMINI_API_KEY = "AIzaSyDOYOVyB6hKL4zAfowSukoZxutMxj2VUzI"
genai.configure(api_key=GEMINI_API_KEY)
model = genai.GenerativeModel("gemini-2.5-flash-lite")

def summarize(headline, content):
    result = [None]
    error  = [None]

    def call():
        try:
            prompt = f"""Summarize the following news article in exactly 60-65 words.
Write in plain, clear North American journalism style.
Start directly with the news — no intro phrases like "This article..." or "The story...".

Headline: {headline}
Article: {content[:3000]}

60-65 word summary:"""
            response = model.generate_content(prompt)
            result[0] = response.text.strip()
        except Exception as e:
            error[0] = str(e)

    t = threading.Thread(target=call)
    t.start()
    t.join(timeout=120)  # 20 second hard limit

    if t.is_alive():
        return "[Summary timed out]"
    if error[0]:
        return f"[Summary error: {error[0][:100]}]"
    return result[0]

import requests
import trafilatura

def safe_scrape(url, timeout_secs=6):
    try:
        headers = {"User-Agent": "Mozilla/5.0"}
        response = requests.get(url, timeout=timeout_secs, headers=headers)
        content = trafilatura.extract(response.text) or "[No content extracted]"
        return content[:5000]
    except requests.exceptions.Timeout:
        return "[Timed out]"
    except Exception as e:
        return f"[Scrape error: {e}]"

import gspread
from google.auth import default

creds, _ = default(scopes=["https://www.googleapis.com/auth/spreadsheets"])
gc = gspread.authorize(creds)

spreadsheet = gc.open_by_key(SPREADSHEET_ID)

try:
    sheet = spreadsheet.worksheet(SHEET_NAME)
    print(f"Found existing sheet: {SHEET_NAME}")
except gspread.WorksheetNotFound:
    sheet = spreadsheet.add_worksheet(SHEET_NAME, rows=1000, cols=8)
    sheet.append_row(
        ["Timestamp", "Source", "Headline", "URL", "Scraped Content", "Status", "AI Draft", "Final Copy"]
    )
    print(f"Created new sheet: {SHEET_NAME}")

# Load existing URLs to skip duplicates
existing_urls = set(sheet.col_values(4)[1:])
print(f"Existing articles in sheet: {len(existing_urls)}")

import requests
import feedparser
import trafilatura
import time
from datetime import datetime, timezone

total_added = 0

for source_name, feed_url in FEEDS:
    print(f"\n📡 [{source_name}] fetching feed...")
    try:
        try:
            feed_response = requests.get(feed_url, timeout=8, headers={"User-Agent": "Mozilla/5.0"})
            feed = feedparser.parse(feed_response.text)
        except requests.exceptions.Timeout:
            print(f"  ❌ Feed timed out, skipping")
            continue

        print(f"  Got {len(feed.entries)} entries")
        count = 0

        for entry in feed.entries:
            if count >= MAX_PER_FEED:
                break
            url   = entry.get("link", "").strip()
            title = entry.get("title", "").strip()
            if not url or not title:
                continue
            if url in existing_urls:
                print(f"  ⏭ SKIP: {title[:70]}")
                continue

            print(f"  Scraping: {url[:80]}")
            content = safe_scrape(url, timeout_secs=6)
            print(f"  Scraped: {len(content)} chars")

            print(f"  Summarizing...")
            time.sleep(5)                          # ← ADDED HERE
            summary = summarize(title, content)
            print(f"  Summary: {summary[:80]}")

            row = [
                datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
                source_name, title, url, content[:5000],
                "PENDING",
                summary,
                "",
            ]
            print(f"  Writing to sheet...")
            sheet.append_row(row, value_input_option="RAW")
            existing_urls.add(url)
            count += 1
            total_added += 1
            print(f"  ✅ ADDED: {title[:70]}")
            time.sleep(0.5)

    except Exception as e:
        print(f"  ❌ FEED ERROR: {e}")

print(f"\n✅ Done. Total added: {total_added}")

for m in genai.list_models():
    if "generateContent" in m.supported_generation_methods:
        print(m.name)

